"""empty message

Revision ID: 19983b94e171
Revises: 4904a2814317
Create Date: 2021-05-06 20:15:57.947800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19983b94e171'
down_revision = '4904a2814317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_online_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('register_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_date')
    op.drop_column('users', 'last_online_date')
    # ### end Alembic commands ###
