"""empty message

Revision ID: 4904a2814317
Revises: 30d5f6313fbd
Create Date: 2021-05-06 20:14:56.704800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4904a2814317'
down_revision = '30d5f6313fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_online_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('register_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_date')
    op.drop_column('users', 'last_online_date')
    # ### end Alembic commands ###
