"""empty message

Revision ID: a4d300481cb5
Revises: 19983b94e171
Create Date: 2021-05-11 19:19:48.233800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d300481cb5'
down_revision = '19983b94e171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
