"""empty message

Revision ID: c3864e9527e0
Revises: ffd555b8b0ea
Create Date: 2021-05-14 19:05:09.240400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3864e9527e0'
down_revision = 'ffd555b8b0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('have_title_image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'have_title_image')
    # ### end Alembic commands ###
